-- migrations/001_init.sql

-- This file creates the entire database schema from scratch.

-- Run it once against the labdatasets database:
--   psql -h localhost -p 5433 -U labuser -d labdatasets -f migrations/001_init.sql

-- Every table has a comment explaining its purpose so anyone reading
-- the schema knows immediately what each piece stores.


-- datasets
-- The central table. One row per uploaded dataset.
-- Most of the rich metadata here is generated by the AI layer at upload time, not typed in by the researcher.

CREATE TABLE IF NOT EXISTS datasets (
    id                  SERIAL PRIMARY KEY,

    -- Basic identity
    name                TEXT        NOT NULL,
    description         TEXT,               -- AI-generated narrative summary

    -- Who uploaded it and when
    researcher_name     TEXT        NOT NULL,
    uploaded_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Physical file information
    -- A dataset may span multiple files (see the files table) but we
    -- store the total size here for quick display without joining.
    total_size_bytes    BIGINT      NOT NULL DEFAULT 0,

    -- Classification metadata — all generated by the AI layer
    modality            TEXT,       -- 'text' | 'image' | 'tabular' | 'audio' | 'multimodal'
    dataset_type        TEXT,       -- 'supervised' | 'unsupervised' | 'semi-supervised' | 'self-supervised'
    annotation_format   TEXT,       -- e.g. 'COCO JSON' | 'YOLO TXT' | 'CSV' | 'none'

    -- Label completeness: a float between 0.0 and 1.0
    -- 1.0 = fully labeled, 0.0 = fully unlabeled, 0.99 = 99 % labeled
    -- Estimated by the AI layer at upload time.
    -- Surfaced in search results so researchers know before downloading.
    label_completeness  REAL        NOT NULL DEFAULT 0.0,

    -- Free-form tags the researcher can add (stored as a text array)
    tags                TEXT[]      NOT NULL DEFAULT '{}',

    -- Search support columns
    -- ai_summary is the full generated summary fed into the search indexes.
    -- It is separate from description so we can update search content
    -- without touching the human-visible description.
    ai_summary          TEXT,

    -- Status tracks where this dataset is in the ingestion pipeline.
    -- 'pending'    = files still uploading
    -- 'processing' = AI layer running
    -- 'ready'      = fully indexed and searchable
    -- 'error'      = something went wrong; error_message has details
    status              TEXT        NOT NULL DEFAULT 'pending',
    error_message       TEXT,

    -- Vector embedding stored as a raw float array.
    -- pgvector would be cleaner but requires an extension we may not
    -- have. We store embeddings in a separate search index file instead
    -- and keep only the dataset id here for cross-referencing.
    -- This column is intentionally left out for now and handled by the
    -- search service externally.

    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index on researcher name for the common filter "show me datasets from researcher X"
CREATE INDEX IF NOT EXISTS idx_datasets_researcher ON datasets(researcher_name);

-- Index on modality and dataset_type for filter queries
CREATE INDEX IF NOT EXISTS idx_datasets_modality      ON datasets(modality);
CREATE INDEX IF NOT EXISTS idx_datasets_dataset_type  ON datasets(dataset_type);
CREATE INDEX IF NOT EXISTS idx_datasets_status        ON datasets(status);

-- Full-text search index on the columns researchers are most likely to
-- search by keyword. This powers the PostgreSQL tsvector approach as a
-- fallback before the dedicated BM25 index is wired in.
-- We index name, description, ai_summary, and researcher_name together.
ALTER TABLE datasets
    ADD COLUMN IF NOT EXISTS search_vector TSVECTOR
    GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(name, '')),        'A') ||
        setweight(to_tsvector('english', coalesce(ai_summary, '')),  'B') ||
        setweight(to_tsvector('english', coalesce(description, '')), 'C') ||
        setweight(to_tsvector('english', coalesce(researcher_name, '')), 'D')
    ) STORED;

CREATE INDEX IF NOT EXISTS idx_datasets_fts ON datasets USING GIN(search_vector);

-- ----------------------------------------------------------------
-- labels
--
-- Each dataset can have multiple labels / class names.
-- These are the Weka-style class tags generated by the AI layer.
-- For an image classification dataset, these might be
-- ['cat', 'dog', 'bird'].
-- For a sentiment dataset, ['positive', 'negative', 'neutral'].
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS labels (
    id          SERIAL PRIMARY KEY,
    dataset_id  INTEGER NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,

    -- The class name itself, e.g. 'cat' or 'positive'
    label_name  TEXT    NOT NULL,

    -- What fraction of samples belong to this class (0.0 to 1.0)
    -- NULL means we know the class exists but not its distribution.
    proportion  REAL,

    -- How many samples have this label (-1 = unknown)
    sample_count BIGINT NOT NULL DEFAULT -1
);

CREATE INDEX IF NOT EXISTS idx_labels_dataset ON labels(dataset_id);

-- ----------------------------------------------------------------
-- pseudo_queries
--
-- These are the example search questions generated by the AI layer
-- at upload time (5–10 per dataset).
--
-- The idea comes from Terrenzi et al. 2026: generating hypothetical
-- questions a researcher might ask when looking for this dataset
-- dramatically reduces vocabulary mismatch at search time.
-- These questions are fed into the BM25 index alongside the
-- description and summary.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pseudo_queries (
    id          SERIAL  PRIMARY KEY,
    dataset_id  INTEGER NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    query_text  TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pseudo_queries_dataset ON pseudo_queries(dataset_id);

-- ----------------------------------------------------------------
-- files
--
-- A dataset can consist of multiple physical files.
-- This table tracks each file individually so we can report on
-- partial uploads, resume interrupted transfers, and list files
-- within a dataset.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS files (
    id              SERIAL  PRIMARY KEY,
    dataset_id      INTEGER NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,

    -- Original filename as the researcher named it
    original_name   TEXT    NOT NULL,

    -- Where it lives on John's filesystem after upload completes
    storage_path    TEXT    NOT NULL,

    -- Size of this individual file in bytes
    size_bytes      BIGINT  NOT NULL DEFAULT 0,

    -- MIME type detected at upload time (may be application/octet-stream
    -- for unknown binary formats — that is fine)
    mime_type       TEXT,

    -- Upload state for this specific file
    -- 'uploading' | 'complete' | 'error'
    upload_status   TEXT    NOT NULL DEFAULT 'uploading',

    uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_files_dataset ON files(dataset_id);

ALTER TABLE datasets ADD COLUMN IF NOT EXISTS embedding_json TEXT;