package mlexport

import (
	"fmt"
	"strings"
	"time"
)

// renderDatasheet produces README.md: a datasheet covering provenance,
// contents, schema, labels, known biases, splits, and how to reproduce
// processed/ from raw/. Sections whose facts DMS cannot know (source,
// license, collection method) say so explicitly instead of guessing.
func renderDatasheet(spec *PackageSpec, m *Manifest) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# %s — ML Package", spec.Name)
	w("")
	w("Generated by DMS on %s. Parts of this datasheet (summary, modality,", m.GeneratedAt.Format("2006-01-02"))
	w("labels, completeness) were produced by AI analysis of file samples and")
	w("should be verified before publication.")
	w("")

	w("## Overview")
	w("")
	if spec.AISummary != "" {
		w("%s", spec.AISummary)
	} else {
		w("_No AI summary available._")
	}
	w("")
	if spec.Modality != "" || spec.DatasetType != "" {
		w("- **Modality:** %s", orUnknown(spec.Modality))
		w("- **Dataset type:** %s", orUnknown(spec.DatasetType))
		w("- **Annotation format:** %s", orUnknown(spec.AnnotationFormat))
		w("- **Label completeness (estimated):** %.0f%%", spec.LabelCompleteness*100)
		if len(spec.Tags) > 0 {
			w("- **Tags:** %s", strings.Join(spec.Tags, ", "))
		}
		w("")
	}

	w("## Provenance")
	w("")
	w("- **Uploaded by:** %s", spec.ResearcherName)
	w("- **Uploaded at:** %s", spec.UploadedAt.Format(time.RFC3339))
	if strings.TrimSpace(spec.Description) != "" {
		w("- **Uploader's description:** %s", strings.TrimSpace(spec.Description))
	} else {
		w("- **Uploader's description:** _not provided_")
	}
	w("- **Source / collection method:** _not documented in DMS — contact the uploader._")
	w("- **License:** _not specified — confirm with the uploader before redistribution._")
	w("")

	w("## Contents")
	w("")
	w("`raw/` holds every file exactly as uploaded — never edited. All checksums are SHA-256 (full digests in `manifest.json`).")
	w("")
	w("| File | Size (bytes) | Type | Role | SHA-256 (prefix) |")
	w("|---|---:|---|---|---|")
	for _, f := range m.Files {
		w("| `%s` | %d | %s | %s | `%s` |", f.Path, f.SizeBytes, orUnknown(f.DetectedType), orUnknown(f.Role), shortHash(f.Sha256))
	}
	w("")

	w("## Processed data")
	w("")
	if m.Schema.Mode == "tabular" {
		w("`processed/` contains `train.parquet`, `val.parquet`, and `test.parquet`.")
		w("Every value is stored as a **string** (column `%s` is the sample ID);", m.Schema.IDColumn)
		w("the inferred types below are advisory and come from sampled profiling.")
		w("")
		w("| Column | Stored type | Inferred type |")
		w("|---|---|---|")
		for _, c := range m.Schema.Columns {
			w("| `%s` | %s | %s |", c.Name, c.StoredType, orUnknown(c.InferredType))
		}
	} else {
		w("`processed/` contains `train.jsonl`, `val.jsonl`, and `test.jsonl`. Each")
		w("line references one sample file via a package-relative path into `raw/`")
		w("(files are not duplicated inside the package). Annotation and metadata")
		w("files remain in `raw/` untouched.")
	}
	w("")

	w("## Labels")
	w("")
	if len(spec.Labels) == 0 {
		w("_No label classes were identified._")
	} else {
		w("| Label | Proportion | Sample count |")
		w("|---|---:|---:|")
		for _, l := range spec.Labels {
			prop := "unknown"
			if l.Proportion != nil {
				prop = fmt.Sprintf("%.1f%%", *l.Proportion*100)
			}
			count := "unknown"
			if l.SampleCount >= 0 {
				count = fmt.Sprintf("%d", l.SampleCount)
			}
			w("| %s | %s | %s |", l.Name, prop, count)
		}
	}
	w("")

	w("## Known biases and caveats")
	w("")
	wrote := false
	if imbalance := describeImbalance(spec.Labels); imbalance != "" {
		w("- %s", imbalance)
		wrote = true
	}
	for _, c := range spec.AICaveats {
		if strings.TrimSpace(c) != "" {
			w("- %s", strings.TrimSpace(c))
			wrote = true
		}
	}
	w("- Metadata in this datasheet was inferred by AI from bounded file samples and may be incomplete or wrong.")
	_ = wrote
	w("")

	w("## Splits")
	w("")
	if m.Split.Method == SplitMethodProvided {
		w("The uploader shipped explicit train/validation/test files; the split")
		w("assignment follows those files. See `splits/%s`.", SplitFileName)
	} else {
		w("Samples were assigned by a deterministic seeded hash rule (seed %d,", m.Split.Seed)
		w("ratios %.0f/%.0f/%.0f): `frac = uint64(sha256(\"<seed>:<id>\")[0:8]) / 2^64`,",
			TrainRatio*100, ValRatio*100, (1-TrainRatio-ValRatio)*100)
		w("then `frac < %.1f → train`, `< %.1f → val`, else `test`.", TrainRatio, TrainRatio+ValRatio)
	}
	w("")
	w("| Split | Samples |")
	w("|---|---:|")
	w("| train | %d |", m.Counts.Samples.Train)
	w("| val | %d |", m.Counts.Samples.Val)
	w("| test | %d |", m.Counts.Samples.Test)
	w("")
	w("`splits/%s` is the authoritative record — **the split is data, not code**.", SplitFileName)
	w("")

	w("## Reproducing processed/ from raw/")
	w("")
	w("```")
	w("python3 scripts/build.py            # requires: pip install pyarrow")
	w("```")
	w("")
	w("`build.py` is deterministic: it re-reads `raw/`, applies the recorded")
	w("split (explicit IDs when present, otherwise the seeded hash rule) and")
	w("rewrites `processed/`. It reads all parameters from `manifest.json` and")
	w("`splits/%s`.", SplitFileName)
	w("")

	w("## Package layout")
	w("")
	w("```")
	w("%s/", spec.Slug)
	w("├── README.md          # this datasheet")
	w("├── manifest.json      # version, checksums, counts, schema, labels")
	w("├── raw/               # exactly as uploaded — never edited")
	w("├── processed/         # train/val/test, ready for ML")
	w("├── splits/%s", SplitFileName)
	w("└── scripts/build.py   # raw → processed, deterministic, seeded")
	w("```")
	return b.String()
}

func orUnknown(s string) string {
	if strings.TrimSpace(s) == "" {
		return "unknown"
	}
	return s
}

func shortHash(sum string) string {
	sum = strings.TrimPrefix(sum, "sha256:")
	if len(sum) > 12 {
		return sum[:12]
	}
	return sum
}

// describeImbalance flags strong class imbalance from the label proportions.
func describeImbalance(labels []LabelDef) string {
	var min, max *LabelDef
	for i := range labels {
		l := labels[i]
		if l.Proportion == nil || *l.Proportion <= 0 {
			continue
		}
		if min == nil || *l.Proportion < *min.Proportion {
			min = &labels[i]
		}
		if max == nil || *l.Proportion > *max.Proportion {
			max = &labels[i]
		}
	}
	if min == nil || max == nil || min == max {
		return ""
	}
	ratio := *max.Proportion / *min.Proportion
	if ratio < 3 {
		return ""
	}
	return fmt.Sprintf(
		"Class imbalance: %q (%.1f%%) is %.0f× more frequent than %q (%.1f%%). Consider stratified evaluation or reweighting.",
		max.Name, *max.Proportion*100, ratio, min.Name, *min.Proportion*100)
}
